/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.CuentaExistente;
import Modelo.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joshu
 */
public class AñadirCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AñadirCuenta
     */
    Sucursal s;
    Cliente c;
    public AñadirCuenta() {
        initComponents();
        this.jButton1.setToolTipText("Abrir Cuenta");
        cargarComboBox();
    }
    
    public AñadirCuenta(Sucursal suc, Cliente cl){
        initComponents();
        this.jButton1.setToolTipText("Abrir Cuenta");
        cargarComboBox();
        this.s = suc;
        this.c = cl;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de cuenta");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/acceptar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Añadir cuenta
        String tipo;
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        if(!this.jComboBox1.getSelectedItem().equals("- Seleccion Tipo -")){
            tipo = (String) this.jComboBox1.getSelectedItem();
            switch(tipo){
                case "Cuenta Corriente":
                    try{
                        cc = new CuentaCorriente(this.c.getNumC()+1,0,0);
                        this.c.altaCuenta(cc);    
                        Controlador.GestionBanco.añadirCuenta(this.s, this.c, cc.getNumCuenta(), "FI");
                    } catch (CuentaExistente ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido añadir el cliente");
                    }
                    break;
                case "Cuenta Vivienda":
                    try{
                        cv = new CuentaVivienda(this.c.getNumC()+1,0,0);
                        this.c.altaCuenta(cv);
                        Controlador.GestionBanco.añadirCuenta(this.s, this.c, cv.getNumCuenta(), "FI");
                    } catch (CuentaExistente ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido añadir el cliente");
                    }
                    break;
                case "Fondo Inversión":
                    try {
                        fi = new FondoInversion(this.c.getNumC()+1,0,0);
                        this.c.altaCuenta(fi);
                        Controlador.GestionBanco.añadirCuenta(this.s, this.c, fi.getNumCuenta(), "FI");
                    } catch (CuentaExistente ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido añadir el cliente");
                    }
                    break;
            }
            GestiónCuentas gc = new GestiónCuentas(this.s,this.c);
            gc.setLocation(500,0);
            gc.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"No has seleccionado el tipo de cuenta");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargarComboBox(){
        this.jComboBox1.removeAllItems();
        this.jComboBox1.addItem("- Seleccion Tipo -");
        this.jComboBox1.addItem("Cuenta Corriente");
        this.jComboBox1.addItem("Cuenta Vivienda");
        this.jComboBox1.addItem("Fondo Inversión");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
