/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.NoExisteCuenta;
import Modelo.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joshu
 */
public class GestiónCuentas extends javax.swing.JFrame {

    /**
     * Creates new form GestiónCuentas
     */
    Sucursal s;
    Cliente c;
    private DefaultTableModel modelTaula;
    public GestiónCuentas() {
        initComponents();
        this.jButton1.setToolTipText("Abrir Cuenta");
        this.jButton2.setToolTipText("Cerrar Cuenta");
        this.jButton3.setToolTipText("Sacar Dinero");
        this.jButton4.setToolTipText("Ingresar Dinero");
        this.jButton5.setToolTipText("Realizar Transferencia");
        this.jButton6.setToolTipText("Pedir Préstamo");
        this.jButton7.setToolTipText("Revisión Mensual");
        this.jButton8.setToolTipText("Volver a Clientes");
        this.jButton9.setToolTipText("Ver Movimientos");
    }
    
    public GestiónCuentas(Sucursal suc, Cliente cl){
        initComponents();
        this.jButton1.setToolTipText("Abrir Cuenta");
        this.jButton2.setToolTipText("Cerrar Cuenta");
        this.jButton3.setToolTipText("Sacar Dinero");
        this.jButton4.setToolTipText("Ingresar Dinero");
        this.jButton5.setToolTipText("Realizar Transferencia");
        this.jButton6.setToolTipText("Pedir Préstamo");
        this.jButton7.setToolTipText("Revisión Mensual");
        this.jButton8.setToolTipText("Volver a Clientes");
        this.jButton9.setToolTipText("Ver Movimientos");
        this.s = suc;
        this.c = cl;
        modelTaula = new DefaultTableModel();
        modelTaula.addColumn("Nº Cuenta");
        modelTaula.addColumn("Tipo Cuenta");
        modelTaula.addColumn("Saldo");
        modelTaula.addColumn("Puntos");
        this.jTable1.setModel(modelTaula);
        this.jLabel1.setText("Cuentas del cliente "+this.c.getNom());
        plenarTaula();
    }
    
    public void actualitzar(){
        modelTaula = new DefaultTableModel();
        modelTaula.addColumn("Nº Cuenta");
        modelTaula.addColumn("Tipo Cuenta");
        modelTaula.addColumn("Saldo");
        modelTaula.addColumn("Puntos");
        this.jTable1.setModel(modelTaula);
        this.jLabel1.setText("Cuentas del cliente "+this.c.getNom());
        plenarTaula();
    }

    public void plenarTaula(){
        Vector info;
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        for(int i = 0; i < this.c.getCuentas().size(); i++){
            info =  new Vector();
            if(this.c.getCuentas().get(i) instanceof CuentaCorriente){
                cc = (CuentaCorriente) this.c.getCuentas().get(i);
                info.add(cc.getNumCuenta());
                info.add("Cuenta Corriente");
                info.add(cc.getSaldo());
                info.add(cc.getPuntos());
                modelTaula.addRow(info);
            }else if(this.c.getCuentas().get(i) instanceof CuentaVivienda){
                cv = (CuentaVivienda) this.c.getCuentas().get(i);
                info.add(cv.getNumCuenta());
                info.add("Cuenta Vivienda");
                info.add(cv.getSaldo());
                info.add(cv.getPuntos());
                modelTaula.addRow(info);
            }else if(this.c.getCuentas().get(i) instanceof FondoInversion){
                fi =  (FondoInversion) this.c.getCuentas().get(i);
                info.add(fi.getNumCuenta());
                info.add("Fondo Inversión");
                info.add(fi.getSaldo());
                info.add(fi.getPuntos());
                modelTaula.addRow(info);
            }
            jTable1.setModel(modelTaula);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tarjeta-de-credito.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-eliminar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/sacar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ingresar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/transferir-dinero.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prestamo.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/revision_mensual.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/flecha-izquierda-curva.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/analisis.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jButton7)
                        .addGap(65, 65, 65)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Eliminar Cuenta
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
        String tipo = this.jTable1.getValueAt(row, 1).toString(),numC = this.jTable1.getValueAt(row, 0).toString();
        if(tipo.equals("Cuenta Corriente")){
            cc = (CuentaCorriente) this.c.buscarCuenta(Integer.parseInt(numC));
            try{
                this.c.borrarCuenta(cc);
                Controlador.GestionBanco.borrarCuenta(this.s, this.c, Integer.parseInt(numC));
                actualitzar();
            }catch(NoExisteCuenta ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
        }else if(tipo.equals("Cuenta Vivienda")){
            cv = (CuentaVivienda) this.c.buscarCuenta(Integer.parseInt(numC));
            try{
                this.c.borrarCuenta(cv);
                Controlador.GestionBanco.borrarCuenta(this.s, this.c, Integer.parseInt(numC));
                actualitzar();
            }catch(NoExisteCuenta ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
        }else if(tipo.equals("Fondo Inversión")){
            fi = (FondoInversion) this.c.buscarCuenta(Integer.parseInt(numC));
            try{
                this.c.borrarCuenta(fi);
                Controlador.GestionBanco.borrarCuenta(this.s, this.c, Integer.parseInt(numC));
                actualitzar();
            }catch(NoExisteCuenta ex) {
                JOptionPane.showMessageDialog(this,ex);
            }
        }
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Añadir Cuenta
        AñadirCuenta ac = new AñadirCuenta(this.s,this.c);
        ac.setLocation(500,0);
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Sacar Dinero
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        int num = 0;
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
        String tipo = this.jTable1.getValueAt(row, 1).toString(),numC = this.jTable1.getValueAt(row, 0).toString();
        if(tipo.equals("Cuenta Corriente")){
            cc = (CuentaCorriente) this.c.buscarCuenta(Integer.parseInt(numC));
            num = cc.getNumCuenta();
        }else if(tipo.equals("Cuenta Vivienda")){
            cv = (CuentaVivienda) this.c.buscarCuenta(Integer.parseInt(numC));
            num = cv.getNumCuenta();
        }else if(tipo.equals("Fondo Inversión")){
            fi = (FondoInversion) this.c.buscarCuenta(Integer.parseInt(numC));
            num = fi.getNumCuenta();
        }
        ModSaldo ms = new ModSaldo(false,this.s,this.c,num);
        ms.setLocation(500,0);
        ms.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Ingresar Dinero
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        int num = 0;
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
        String tipo = this.jTable1.getValueAt(row, 1).toString(),numC = this.jTable1.getValueAt(row, 0).toString();
        if(tipo.equals("Cuenta Corriente")){
            cc = (CuentaCorriente) this.c.buscarCuenta(Integer.parseInt(numC));
            num = cc.getNumCuenta();
        }else if(tipo.equals("Cuenta Vivienda")){
            cv = (CuentaVivienda) this.c.buscarCuenta(Integer.parseInt(numC));
            num = cv.getNumCuenta();
        }else if(tipo.equals("Fondo Inversión")){
            fi = (FondoInversion) this.c.buscarCuenta(Integer.parseInt(numC));
            num = fi.getNumCuenta();
        }
        ModSaldo ms = new ModSaldo(true,this.s,this.c,num);
        ms.setLocation(500,0);
        ms.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Realizar Transferencia
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
            String numC = this.jTable1.getValueAt(row, 0).toString();
            Transferencia tf = new Transferencia(this.s,this.c,Integer.parseInt(numC));
            tf.setLocation(500,0);
            tf.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Pedir préstamo
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
            String numC = this.jTable1.getValueAt(row, 0).toString();
            PedirPrestamo psoe = new PedirPrestamo(this.s,this.c,Integer.parseInt(numC));
            psoe.setLocation(500,0);
            psoe.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //Revisión Mensual
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
            String numC = this.jTable1.getValueAt(row, 0).toString();
            RevisiónMensual rm = new RevisiónMensual(this.s,this.c,Integer.parseInt(numC));
            rm.setLocation(500,0);
            rm.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Volver a atrás
        GestiónClientes gc = new GestiónClientes(this.s);
        gc.setLocation(500,0);
        gc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Mostrar Movimientos realizados en la cuenta seleccionada
        int row = this.jTable1.getSelectedRow();
        if(row != -1){
            MostrarMovimientosCuenta mmc = new MostrarMovimientosCuenta(this.s,this.c,Integer.parseInt(this.jTable1.getValueAt(row, 0).toString()));
            mmc.setLocation(500,0);
            mmc.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Debes seleccionar una cuenta");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestiónCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestiónCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestiónCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestiónCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestiónCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
