/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Excepciones.NoExisteCliente;
import Excepciones.TieneCuentas;
import Modelo.Banco;
import Modelo.Cliente;
import Modelo.Sucursal;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joshu
 */
public class GestiónClientes extends javax.swing.JFrame {

    /**
     * Creates new form GestiónClientes
     * @param s
     */
    Sucursal s;
    private DefaultTableModel modelTaula;
    public GestiónClientes() {
        initComponents();
        this.jButton1.setToolTipText("Volver a Sucursales");
        this.jButton3.setToolTipText("Alta Cliente");
        this.jButton4.setToolTipText("Modificar cliente");
        this.jButton5.setToolTipText("Acceso cuentas");
        this.jButton6.setToolTipText("Baja Cliente");
        modelTaula = new DefaultTableModel();
        modelTaula.addColumn("DNI");
        modelTaula.addColumn("Nombre");
        modelTaula.addColumn("Apellidos");
        modelTaula.addColumn("Dirección");
        modelTaula.addColumn("Teléfono");
        modelTaula.addColumn("Nº Cuentas");
        jTable1.setModel(modelTaula);
    }
    
    public GestiónClientes(Sucursal suc){
        this.s = suc;
        initComponents();
        this.jButton1.setToolTipText("Volver a Sucursales");
        this.jButton3.setToolTipText("Baja Cliente");
        this.jButton4.setToolTipText("Alta Cliente");
        this.jButton5.setToolTipText("Acceso cuentas");
        this.jButton6.setToolTipText("Modificar cliente");
        jLabel2.setText("Clientes sucursal "+suc.getCod());
        modelTaula = new DefaultTableModel();
        modelTaula.addColumn("DNI");
        modelTaula.addColumn("Nombre");
        modelTaula.addColumn("Apellidos");
        modelTaula.addColumn("Dirección");
        modelTaula.addColumn("Teléfono");
        modelTaula.addColumn("Nº Cuentas");
        jTable1.setModel(modelTaula);
        plenarTaula(suc);
    }
    
    public void actualitzar(){
        modelTaula = new DefaultTableModel();
        modelTaula.addColumn("DNI");
        modelTaula.addColumn("Nombre");
        modelTaula.addColumn("Apellidos");
        modelTaula.addColumn("Dirección");
        modelTaula.addColumn("Teléfono");
        modelTaula.addColumn("Nº Cuentas");
        jTable1.setModel(modelTaula);
        plenarTaula(this.s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Clientes");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("   PIN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-eliminar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo_cliente.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proximo.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar_cliente.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/flecha-izquierda-curva.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // Intro PIN
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Añadir Cliente
        AñadirCliente ac = new AñadirCliente(this.s);
        ac.setLocation(500,0);
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Modificar Cliente
        String pin;
        int row = this.jTable1.getSelectedRow();
        if(row > -1){
            String dni = this.jTable1.getValueAt(row, 0).toString();
            Cliente c = (Cliente) this.s.buscarCliente(dni);
            if(!this.jPasswordField1.getText().equals("")){
                pin = this.jPasswordField1.getText();
            if(c.compPin(Integer.parseInt(pin))){
            ModificarCliente mc = new ModificarCliente(c, this.s);
            mc.setLocation(500,0);
            mc.setVisible(true);
            this.dispose();
            }else{
                this.jPasswordField1.setText("");
                JOptionPane.showMessageDialog(this, "Pin incorrecto");
            }
            }else{
                JOptionPane.showMessageDialog(this, "Introduce el pin de "+c.getNom());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Acceder a las cuentas del cliente y a su gestión
        String pin;
        int row = this.jTable1.getSelectedRow();
        if(row > -1){
            String dni = this.jTable1.getValueAt(row, 0).toString();
            Cliente c = (Cliente) this.s.buscarCliente(dni);
            if(!this.jPasswordField1.getText().equals("")){
                pin = this.jPasswordField1.getText();
            if(c.compPin(Integer.parseInt(pin))){
                GestiónCuentas gCu = new GestiónCuentas(this.s,c);
                gCu.setLocation(500,0);
                gCu.setVisible(true);
                this.dispose();
            }else{
                this.jPasswordField1.setText("");
                JOptionPane.showMessageDialog(this, "Pin incorrecto");
            }
            }else{
                JOptionPane.showMessageDialog(this, "Introduce el pin de "+c.getNom());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Borrar cliente
        String pin;
        boolean b = false;
        int row = this.jTable1.getSelectedRow();
        if(row > -1){
            String dni = this.jTable1.getValueAt(row, 0).toString();
            Cliente c = (Cliente) this.s.buscarCliente(dni);
            if(!this.jPasswordField1.getText().equals("")){
                pin = this.jPasswordField1.getText();
            if(c.compPin(Integer.parseInt(pin))){
                try{
                        Controlador.GestionBanco.borrarCliente(this.s, c);
                        b = true;
                } catch (TieneCuentas ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    }
                try {
                    if(b){
                        this.s.borrarCliente(c);
                        actualitzar();
                    }
                    } catch (NoExisteCliente ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    }
            }else{
                this.jPasswordField1.setText("");
                JOptionPane.showMessageDialog(this, "Pin incorrecto");
            }
            }else{
                JOptionPane.showMessageDialog(this, "Introduce el pin de "+c.getNom());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrincipal mp = new MenuPrincipal();
        mp.setLocation(500,0);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void plenarTaula(Sucursal s){
        ArrayList<Cliente> clientes = s.getClientes();
        Vector info;
        for(Cliente cl : clientes){
            info =  new Vector();
            info.add(cl.getDni());
            info.add(cl.getNom());
            info.add(cl.getAp());
            info.add(cl.getDir());
            info.add(cl.getTlf());
            info.add(cl.getNumC());
            modelTaula.addRow(info);
            jTable1.setModel(modelTaula);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestiónClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestiónClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestiónClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestiónClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestiónClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
