/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joshu
 */
public class PedirPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form PedirPrestamo
     */
    Sucursal s;
    Cliente c;
    int nc;
    
    public PedirPrestamo(){
        initComponents();
        this.jButton1.setToolTipText("Pedir Préstamo");
    }
    
    public PedirPrestamo(Sucursal suc, Cliente cl, int numC) {
        initComponents();
        this.jButton1.setToolTipText("Pedir Préstamo");
        this.s = suc;
        this.c = cl;
        this.nc = numC;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduce la cantidad");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prestamo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Pedir préstamo
        CuentaCorriente cc;
        CuentaVivienda cv;
        FondoInversion fi;
        int prestamo = Integer.parseInt(this.jTextField1.getText());
        double saldoSucursal = (this.s.getSaldo()-this.s.calcDineroClientes())/this.s.getClientes().size();
        if(saldoSucursal > prestamo){
            if(this.c.buscarCuenta(this.nc) != null){
                if(this.c.buscarCuenta(this.nc) instanceof CuentaCorriente){
                    cc = (CuentaCorriente) this.c.buscarCuenta(this.nc);
                    cc.prestamo(prestamo);
                    try {
                        Controlador.GestionBanco.modSaldoCuenta(this.s, this.c, this.nc, cc.getSaldo(), cc.getPuntos());
                        Controlador.GestionBanco.guardarAccion(this.s, this.c, this.nc, "PRÉSTAMO", "+"+prestamo);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido transferir el dinero");
                    }
                }else if(this.c.buscarCuenta(this.nc) instanceof CuentaVivienda){
                    cv = (CuentaVivienda) this.c.buscarCuenta(this.nc);
                    cv.prestamo(prestamo);
                    try {
                        Controlador.GestionBanco.modSaldoCuenta(this.s, this.c, this.nc, cv.getSaldo(), cv.getPuntos());
                        Controlador.GestionBanco.guardarAccion(this.s, this.c, this.nc, "PRÉSTAMO", "+"+prestamo);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido transferir el dinero");
                    }
                }else if(this.c.buscarCuenta(this.nc) instanceof FondoInversion){
                    fi = (FondoInversion) this.c.buscarCuenta(this.nc);
                    fi.prestamo(prestamo);
                    try {
                        Controlador.GestionBanco.modSaldoCuenta(this.s, this.c, this.nc,fi.getSaldo(), fi.getPuntos());
                        Controlador.GestionBanco.guardarAccion(this.s, this.c, this.nc, "PRÉSTAMO", "+"+prestamo);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido transferir el dinero");
                    }
                }
                this.s.pedirPrestamo(prestamo);
                try {
                    Controlador.GestionBanco.modSaldoSucursal(this.s);
                } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "No se ha podido transferir el dinero");
                }
                GestiónCuentas gc = new GestiónCuentas(this.s,this.c);
                gc.setLocation(500,0);
                gc.setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(this,"No se ha aceptado el préstamo\nEl importe máximo es de "+saldoSucursal+"€");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedirPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedirPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
